name: ElsClockStrikes CI MSBuild and Test

on:
  push:
    branches: [ "master", "cicd", "feature/*", "fix/*", "refactor/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet packages (Project Dependency)
      run: nuget restore ./ElsClockStrikes.sln

    - name: Build Project
      run: msbuild ./ElsClockStrikes.sln /p:Configuration=Release

    - name: Run tests
      run: |
        $vstest = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
        & $vstest `
          "ElsClockStrikes.Tests\bin\Release\ElsClockStrikes.Tests.dll" `
          "/Logger:Console;Verbosity=detailed"
